# Minikube setup configuration for Todo application
# This file contains the commands and configurations needed to set up Minikube

apiVersion: v1
kind: ConfigMap
metadata:
  name: minikube-setup-config
  namespace: kube-system
data:
  setup-commands.sh: |
    #!/bin/bash
    # Script to set up Minikube for the Todo application
    
    # Start Minikube with recommended resources for this application
    minikube start --driver=docker --cpus=4 --memory=4096mb
    
    # Enable required addons
    minikube addons enable ingress
    minikube addons enable metrics-server
    
    # Verify cluster status
    kubectl cluster-info
    kubectl get nodes
    
    # Create todo-ns namespace
    kubectl create namespace todo-ns
    
    echo "Minikube setup complete!"