# Example raw Kubernetes manifests for the Todo application
# These are alternative to Helm charts, as mentioned in the project structure

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: todo-ns
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-ns
type: Opaque
data:
  # Base64 encoded values
  # DATABASE_URL: <base64-encoded-database-url>
  # GEMINI_API_KEY: <base64-encoded-api-key>
  # JWT_SECRET: <base64-encoded-jwt-secret>
  # BETTER_AUTH_SECRET: <base64-encoded-better-auth-secret>
  # GOOGLE_CLIENT_ID: <base64-encoded-google-client-id>
  # GOOGLE_CLIENT_SECRET: <base64-encoded-google-client-secret>
  # ACCESS_TOKEN_EXPIRE_MINUTES: <base64-encoded-expire-minutes>
  # REFRESH_TOKEN_EXPIRE_DAYS: <base64-encoded-expire-days>
  # GOOGLE_REDIRECT_URI: <base64-encoded-redirect-uri>
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-ns
  labels:
    app: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: backend
        image: todo-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: databaseUrl
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: geminiApiKey
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: jwtSecret
        - name: BETTER_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: betterAuthSecret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: googleClientId
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: googleClientSecret
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: accessTokenExpireMinutes
        - name: REFRESH_TOKEN_EXPIRE_DAYS
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: refreshTokenExpireDays
        - name: GOOGLE_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: googleRedirectUri
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-ns
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo-ns
  labels:
    app: todo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: frontend
        image: todo-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: http://todo-backend-svc:8000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: todo-ns
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: todo-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: todo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-frontend-svc
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: todo-backend-svc
            port:
              number: 80
      - path: /chat
        pathType: Prefix
        backend:
          service:
            name: todo-frontend-svc
            port:
              number: 80