openapi: 3.0.0
info:
  title: AI-Powered Todo Chatbot API
  version: 1.0.0
  description: API for the AI-powered chatbot that allows users to manage their Todo list via natural language

paths:
  /api/{user_id}/chat:
    post:
      summary: Process chat messages from authenticated users
      description: Process chat messages from authenticated users through the OpenAI Agents SDK and return AI-generated responses.
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID of the authenticated user (extracted from JWT)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid request format or missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - user attempting to access another user's endpoint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found - user ID not found in system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error - server processing error, MCP tool failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message to the chatbot
          example: "Remind me to buy groceries"
        thread_id:
          type: string
          description: Optional thread identifier for conversation continuity
          example: "thread-abc123"
        metadata:
          type: object
          description: Additional metadata for the message
          properties:
            timestamp:
              type: string
              format: date-time
              description: ISO 8601 timestamp of the message
            client_info:
              type: string
              description: Information about the client making the request

    ChatResponse:
      type: object
      required:
        - response
        - conversation_id
        - created_at
        - status
      properties:
        response:
          type: string
          description: The AI-generated response to the user's message
          example: "I've added 'buy groceries' to your task list."
        thread_id:
          type: string
          description: Thread identifier for conversation continuity
          example: "thread-abc123"
        conversation_id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
          example: "conv-xyz789"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the response was created
        status:
          type: string
          enum: [success]
          description: Status of the response

    ErrorResponse:
      type: object
      required:
        - error
        - code
        - status
      properties:
        error:
          type: string
          description: Description of the error
        code:
          type: string
          description: Error code
        status:
          type: string
          enum: [error]
          description: Status indicating an error occurred