apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: job-scheduler
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "*/1 * * * *"  # Check for scheduled jobs every minute